name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
        volumes:
          - /var/lib/docker

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r sample-app/backend/requirements.txt

    - name: Lint backend code
      run: |
        # Add linting commands here if needed
        echo "Linting backend code..."

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      run: |
        cd sample-app/frontend
        npm install

    - name: Run frontend build
      run: |
        cd sample-app/frontend
        npm run build
