apiVersion: v1
kind: Service
metadata:
  name: sample-app-backend
spec:
  selector:
    app: sample-app-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-frontend
spec:
  selector:
    app: sample-app-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
